wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.10
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698293690.621988
    t:
      1:
      - 53
      - 55
      2:
      - 53
      - 55
      3:
      - 23
      4: 3.8.17
      5: 0.15.10
      8:
      - 1
      - 5
