wandb_version: 1

path:
  desc: null
  value: genres_mod.parquet
_wandb:
  desc: null
  value:
    python_version: 3.8.17
    cli_version: 0.15.10
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697043267.953352
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.8.17
      5: 0.15.10
      8:
      - 5
